services:  
  fw:
    image: ghcr.io/aiwell-ac5000/fw-ac5000:latest
    restart: unless-stopped
    user: root
    privileged: true
    #depends_on:
    #  - "node-red"
    environment:
      - TZ=Europe/Oslo
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "1" 
  node-red:
    image: ghcr.io/aiwell-ac5000/node-red-ac5000:latest
    container_name: root-node-red-1
    restart: unless-stopped
    user: root
    privileged: true
    environment:
      - TZ=Europe/Oslo
      - PORT=${NODE_PORT}
    network_mode: host
    volumes:
      - node-red-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      #- type: bind
      #  source: /root/logg
      #  target: /logg
      #- type: bind
      #  source: /bin
      #  target: /root/bin
      - type: bind
        source: /root/pipes
        target: /pipes
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /etc
        target: /etc
      - type: bind
        source: /sys/bus/i2c/devices/0-006c/iio:device0
        target: /ai
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "1"     
volumes:
  node-red-data:
