version: "3.8"

services:  
  node-red:
    image: ghcr.io/aiwell-ac5000/node-red-ac5000:pc
    container_name: root-node-red-1
    restart: unless-stopped
    environment:
      - TZ=Europe/Oslo
      - PORT=1880
    volumes:
      - node-red-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"     
volumes:
  node-red-data:
